import Head from 'next/head'
import HomeHeader from '../components/HomeHeader'
import styles from '../styles/Home.module.css'
import HomeNav from '../components/HomeNav'
import apiTmdb from '../apiTmdb'
import Results from '../components/Results'



export default function Home({data}) {
  



  console.log(data)
  return (
    <div className='bg-[#06202A] relative' >
            <Head>
                <title>Stream TV and Movies Live and Online | Hulu</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>
        
            {/* Menu */}
            <HomeHeader />
            <HomeNav/>
            <Results data={data}/>
         

    </div>
  )
}




export async function getServerSideProps(context){


  const {genre}=context.query
  const request = await fetch(`http://api.themoviedb.org/3${apiTmdb[genre]?.url || apiTmdb.fetchTrending.url}`)
  const response=await request.json()

return{props:{data:response.results}}

}