import React from 'react'
import Head from 'next/head'
import PlateformSlogan from '../components/PlateformSlogan'
import Welcome from '../components/Welcome'
const Login = () => {



    return (
        <div>
            <Head>
                <title>Sign In | Hulu</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>
            {/* WELCOME */}
            <Welcome />
            {/* PLATFORM SLOGAN */}
            <PlateformSlogan />




            {/* MARKET PROPOSAL 2 */}
            {/* FOOTER */}
        </div>
    )
}

export default Login